#!/usr/bin/env python3
"""Extract the NBA 2K archetype database from the 2K_to_BBGM_Archetypes.xlsx
workbook into a JS data file consumed by the web app (docs/archetypes.js).

Usage: python3 tools/extract_archetypes.py path/to/2K_to_BBGM_Archetypes.xlsx
"""
import json
import re
import sys

import openpyxl

# 2K stat columns used for matching (order matches Archetype_DB sheet)
STAT_COLS = {
    "Close Shot": 4,
    "Driving Layup": 5,
    "Driving Dunk": 6,
    "Standing Dunk": 7,
    "Post Control": 8,
    "Midrange Shot": 9,
    "Threepoint Shot": 10,
    "Free Throw": 11,
    "Pass Accuracy": 12,
    "Ball Handle": 13,
    "Speed With Ball": 14,
    "Interior Defense": 15,
    "Perimeter Defense": 16,
    "Steal": 17,
    "Block": 18,
    "Offensive Rebound": 19,
    "Defensive Rebound": 20,
    "Speed": 21,
    "Agility": 22,
    "Strength": 23,
    "Vertical": 24,
}

POS_ABBR = {
    "Point Guard": "PG",
    "Shooting Guard": "SG",
    "Small Forward": "SF",
    "Power Forward": "PF",
    "Center": "C",
}


def parse_range(v):
    """Return midpoint of a '70-85' range, or the number itself."""
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return float(v)
    s = str(v).strip()
    m = re.match(r"^(\d+(?:\.\d+)?)\s*-\s*(\d+(?:\.\d+)?)$", s)
    if m:
        return (float(m.group(1)) + float(m.group(2))) / 2
    try:
        return float(s)
    except ValueError:
        return None


def parse_height(v):
    """Parse '6\'4" to 6\'6"' or '6\'6"' into (min_inches, max_inches)."""
    if v is None:
        return None, None
    feet_in = re.findall(r"(\d+)'\s*(\d+)?\"?", str(v))
    if not feet_in:
        return None, None
    inches = [int(f) * 12 + int(i or 0) for f, i in feet_in]
    return min(inches), max(inches)


def main():
    path = sys.argv[1]
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["Archetype_DB"]

    archetypes = []
    for row in ws.iter_rows(min_row=3, values_only=True):
        name = row[0]
        if not name:
            continue
        hmin, hmax = parse_height(row[2])
        stats = {}
        ok = True
        for stat, col in STAT_COLS.items():
            val = parse_range(row[col])
            if val is None:
                ok = False
                break
            stats[stat] = round(val, 2)
        if not ok or hmin is None:
            continue
        archetypes.append({
            "name": name,
            "pos": POS_ABBR.get(row[1], row[1]),
            "hMin": hmin,
            "hMax": hmax,
            "stats": [stats[s] for s in STAT_COLS],
        })

    out = {
        "statNames": list(STAT_COLS),
        "archetypes": archetypes,
    }
    with open("docs/archetypes.js", "w") as f:
        f.write("// Generated by tools/extract_archetypes.py — do not edit by hand\n")
        f.write("const ARCHETYPE_DATA = ")
        json.dump(out, f, separators=(",", ":"))
        f.write(";\n")
    print(f"Wrote {len(archetypes)} archetypes to docs/archetypes.js")


if __name__ == "__main__":
    main()
