#!/usr/bin/env python3
"""Extract the NBA 2K archetype database from the 2K_to_BBGM_Archetypes.xlsx
workbook into a JS data file consumed by the web app (docs/archetypes.js).

Usage: python3 tools/extract_archetypes.py path/to/2K_to_BBGM_Archetypes.xlsx
"""
import argparse
import json
import re
import sys
from pathlib import Path

import openpyxl

# 2K stat columns used for matching (order matches Archetype_DB sheet)
STAT_COLS = {
    "Close Shot": 4,
    "Driving Layup": 5,
    "Driving Dunk": 6,
    "Standing Dunk": 7,
    "Post Control": 8,
    "Midrange Shot": 9,
    "Threepoint Shot": 10,
    "Free Throw": 11,
    "Pass Accuracy": 12,
    "Ball Handle": 13,
    "Speed With Ball": 14,
    "Interior Defense": 15,
    "Perimeter Defense": 16,
    "Steal": 17,
    "Block": 18,
    "Offensive Rebound": 19,
    "Defensive Rebound": 20,
    "Speed": 21,
    "Agility": 22,
    "Strength": 23,
    "Vertical": 24,
}

POS_ABBR = {
    "Point Guard": "PG",
    "Shooting Guard": "SG",
    "Small Forward": "SF",
    "Power Forward": "PF",
    "Center": "C",
}

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "archetypes.js"


def parse_range(v):
    """Return (min, max) of a '70-85' range, or (v, v) for a bare number."""
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return (float(v), float(v))
    s = str(v).strip()
    m = re.match(r"^(\d+(?:\.\d+)?)\s*-\s*(\d+(?:\.\d+)?)$", s)
    if m:
        lo, hi = float(m.group(1)), float(m.group(2))
        return (lo, hi) if lo <= hi else (hi, lo)
    try:
        n = float(s)
        return (n, n)
    except ValueError:
        return None


def parse_height(v):
    """Parse '6\'4" to 6\'6"' or '6\'6"' into (min_inches, max_inches)."""
    if v is None:
        return None, None
    feet_in = re.findall(r"(\d+)'\s*(\d+)?\"?", str(v))
    if not feet_in:
        return None, None
    inches = [int(f) * 12 + int(i or 0) for f, i in feet_in]
    return min(inches), max(inches)


def main():
    parser = argparse.ArgumentParser(
        description="Extract the NBA 2K archetype database into docs/archetypes.js")
    parser.add_argument("workbook", help="path to 2K_to_BBGM_Archetypes.xlsx")
    parser.add_argument("-o", "--output", default=str(DEFAULT_OUTPUT),
                         help=f"output JS path (default: {DEFAULT_OUTPUT})")
    args = parser.parse_args()

    wb = openpyxl.load_workbook(args.workbook, data_only=True)
    ws = wb["Archetype_DB"]

    archetypes = []
    skipped = 0
    for row_num, row in enumerate(ws.iter_rows(min_row=3, values_only=True), start=3):
        name = row[0]
        if not name:
            continue
        hmin, hmax = parse_height(row[2])
        stats = {}
        ok = True
        bad_stat = None
        for stat, col in STAT_COLS.items():
            val = parse_range(row[col])
            if val is None:
                ok = False
                bad_stat = stat
                break
            stats[stat] = (round(val[0], 2), round(val[1], 2))
        if not ok or hmin is None:
            skipped += 1
            reason = f"unparseable '{bad_stat}'" if not ok else "unparseable height"
            print(f"  skipping row {row_num} ({name!r}): {reason}", file=sys.stderr)
            continue
        archetypes.append({
            "name": name,
            "pos": POS_ABBR.get(row[1], row[1]),
            "hMin": hmin,
            "hMax": hmax,
            # each stat is [min, max] of the build's legal range
            "stats": [list(stats[s]) for s in STAT_COLS],
        })

    out = {
        "statNames": list(STAT_COLS),
        "archetypes": archetypes,
    }
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w") as f:
        f.write("// Generated by tools/extract_archetypes.py — do not edit by hand\n")
        f.write("const ARCHETYPE_DATA = ")
        json.dump(out, f, separators=(",", ":"))
        f.write(";\n")
    print(f"Wrote {len(archetypes)} archetypes to {output_path}"
          + (f" ({skipped} row(s) skipped, see above)" if skipped else ""))


if __name__ == "__main__":
    main()
